project:
  type: book

book:
  title: "Statistics Minus The Math"
  subtitle: "An Introduction for the Social Sciences"
  author: "Nathan Favero"
  date: "7/18/2024"
  license: "CC BY"
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - Chapter4.qmd
    - Chapter5.qmd
    - Chapter6.qmd
    - Chapter7.qmd
    - Chapter8.qmd
    - Chapter9.qmd
    - Chapter10.qmd
    - Chapter11.qmd
    - Chapter12.qmd
    - Chapter13.qmd
    # - references.qmd
  
# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    header-includes: |
      \publishers{Get the latest version of this text at: \url{https://minusthemath.com} \bigskip \bigskip \bigskip \bigskip \\
      \href{https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1}{\includegraphics{Images/by.png}}}
    # usepackage: amsmath

# editor: visual
# 
# output:
#   pdf_document:
#     extra_dependencies: "subfig"
# 

